function filter = initCVFilterCustom(detection)
% initCVFilterCustom - Initialize a constant velocity filter using trackingEKFCustom
% This function is a replicate of initCVFilter that returns a
% trackingEKFCustom instead of trackingEKF.
filter = initCVFilter(detection);

% Create a trackingEKFCustom with the same properties
filterCustom = trackingEKFCustom( ...
    'StateTransitionFcn', filter.StateTransitionFcn, ...
    'StateTransitionJacobianFcn', filter.StateTransitionJacobianFcn, ...
    'MeasurementFcn', filter.MeasurementFcn, ...
    'MeasurementJacobianFcn', filter.MeasurementJacobianFcn, ...
    'HasAdditiveProcessNoise', filter.HasAdditiveProcessNoise, ...
    'HasAdditiveMeasurementNoise', filter.HasAdditiveMeasurementNoise, ...
    'State', filter.State, ...
    'StateCovariance', filter.StateCovariance, ...
    'ProcessNoise', filter.ProcessNoise, ...
    'MeasurementNoise', filter.MeasurementNoise);

filter = filterCustom;
end
